version: '3.3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: pragyan-23-app
        restart: always
        ports:
            - '3072:3000'
        networks:
            - pragyan-2024_network

networks:
    pragyan-2024_network:
        external: true
